

name: 'test_release'

on:
  push:
    branches:
      - main

jobs:
  development-release:
    name: 'Test release'
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8.
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
    
    
    - name: Build binary wheel and tarball.
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to PyPi test.
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        

